//! Wire-parity conformance: sealed objects PRODUCED BY THE PYTHON
//! REFERENCE must verify and open in Rust byte-for-byte.
//!
//! `fixtures/sealed_object_vectors.json` is generated by
//! `python/tools/gen_sealed_object_vectors.py` (see fixtures/README.md).
//! Each case carries the sealed wire line verbatim, the key files
//! needed to open it (base64), and the expected plaintext per group.
//! These are VERIFY vectors: sealing is randomized, so determinism is
//! on the unseal side.
//!
//! The Python guard `python/tests/test_sealed_object_vectors.py`
//! re-verifies and re-opens the same committed vectors, closing the
//! cross-implementation loop.

#![cfg(feature = "fs")]

use std::collections::BTreeMap;
use std::fs;

use base64::engine::general_purpose::STANDARD;
use base64::Engine as _;
use serde_json::Value;

use tn_core::runtime::unseal_as_recipient;
use tn_core::sealed_object::{extract_group_blocks, parse_sealed_source, verify_sealed};
use tn_core::Error;

#[derive(serde::Deserialize)]
struct Fixture {
    cases: Vec<Case>,
    tampered: Vec<Tampered>,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    /// `"btn"` or `"hibe"` — hibe cases are skipped when the feature is off.
    cipher: String,
    /// The sealed object's wire line, verbatim from Python `str(sealed)`.
    wire: String,
    /// Key files to open it: filename → base64 bytes.
    keys: BTreeMap<String, String>,
    /// Expected decrypted body per group.
    open_groups: BTreeMap<String, Value>,
    /// Expected public fields surfacing verbatim on the envelope.
    public: BTreeMap<String, Value>,
}

#[derive(serde::Deserialize)]
struct Tampered {
    name: String,
    wire: String,
    expected_failed_checks: Vec<String>,
}

fn load_fixture() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/sealed_object_vectors.json"
    );
    serde_json::from_slice(&fs::read(path).expect("fixture file present"))
        .expect("fixture parses")
}

#[test]
fn python_sealed_objects_verify_and_open() {
    let fixture = load_fixture();
    assert!(!fixture.cases.is_empty(), "fixture must carry cases");

    for case in &fixture.cases {
        if case.cipher == "hibe" && !cfg!(feature = "hibe") {
            continue;
        }

        // 1. Parse + self-describing verify. The container/unicode
        //    public cases are the end-to-end R1 proof: Python hashed
        //    them as str(value); the Rust recompute must agree.
        let env = parse_sealed_source(&case.wire)
            .unwrap_or_else(|e| panic!("case={}: parse failed: {e}", case.name));
        let blocks = extract_group_blocks(&env)
            .unwrap_or_else(|e| panic!("case={}: block extraction failed: {e}", case.name));
        let valid = verify_sealed(&env, &blocks);
        assert!(valid.signature, "case={}: signature must verify", case.name);
        assert!(
            valid.row_hash,
            "case={}: Python row_hash must recompute in Rust (container/unicode \
             public values hash as Python str(value))",
            case.name
        );

        // 2. Expected public fields surface verbatim.
        for (k, v) in &case.public {
            assert_eq!(
                env.get(k),
                Some(v),
                "case={}: public key {k:?} must surface verbatim",
                case.name
            );
        }

        // 3. Open every expected group with the provided key files via
        //    the R4 walk primitives (candidate loading + AAD-bound
        //    decrypt), one group per as-recipient call.
        let td = tempfile::tempdir().unwrap();
        for (fname, b64) in &case.keys {
            fs::write(
                td.path().join(fname),
                STANDARD.decode(b64).expect("fixture key bytes decode"),
            )
            .unwrap();
        }
        for (group, expected) in &case.open_groups {
            let out = unseal_as_recipient(&case.wire, td.path(), group, true)
                .unwrap_or_else(|e| panic!("case={} group={group}: unseal failed: {e}", case.name));
            assert!(out.valid.signature && out.valid.row_hash, "case={}", case.name);
            assert_eq!(
                out.plaintext.get(group),
                Some(expected),
                "case={} group={group}: decrypted body must match Python's",
                case.name
            );
        }
    }
}

#[test]
fn python_tampered_objects_fail_expected_checks() {
    let fixture = load_fixture();
    assert!(!fixture.tampered.is_empty(), "fixture must carry tampered cases");

    for t in &fixture.tampered {
        // Empty keystore: the verify gate fires before any key loading.
        let td = tempfile::tempdir().unwrap();
        let err = unseal_as_recipient(&t.wire, td.path(), "default", true)
            .expect_err("tampered object must fail verification");
        match err {
            Error::SealedObjectVerify { failed_checks, .. } => assert_eq!(
                failed_checks, t.expected_failed_checks,
                "case={}: failed-check set and ORDER must match Python's",
                t.name
            ),
            other => panic!("case={}: expected SealedObjectVerify, got {other:?}", t.name),
        }
    }
}
