from typing import Protocol, Sequence, overload
from os import PathLike
from pathlib import Path
from tn.governed import (UseContext, Governance, GovernedObject, DatasetSelection, Session,
                         ObjectRegisters, AdmissionContext, AttachmentContext, ReleaseContext)

class ApplicationIdentity:
    @property
    def application(self) -> str: ...
    @property
    def did(self) -> str: ...
class IdentityProvider(Protocol):
    def resolve(self, application: str) -> ApplicationIdentity: ...
class LocalIdentity:
    def __init__(self, application: str) -> None: ...
    @staticmethod
    def from_private_bytes(application: str, seed: bytes) -> LocalIdentity: ...
    def resolve(self, application: str) -> ApplicationIdentity: ...

class GroupCapability:
    @staticmethod
    def hibe(group: str, public: bytes, path: str, readers: Sequence[bytes], index: bytes) -> GroupCapability: ...
    @staticmethod
    def jwe(group: str, recipients: Sequence[bytes], readers: Sequence[bytes], index: bytes) -> GroupCapability: ...
    @staticmethod
    def btn_reader(group: str, kits: Sequence[bytes], index: bytes) -> GroupCapability: ...
    @staticmethod
    def btn_publisher(group: str, state: bytes, kits: Sequence[bytes], index: bytes) -> GroupCapability: ...
    @property
    def group(self) -> str: ...
class KeySet:
    def __init__(self, identity: ApplicationIdentity, groups: Sequence[GroupCapability]) -> None: ...
    @property
    def owner(self) -> str: ...
    @property
    def groups(self) -> list[str]: ...
class KeyProvider(Protocol):
    def resolve(self, identity: ApplicationIdentity) -> KeySet: ...
class LocalKeys:
    def __init__(self, groups: Sequence[str]) -> None: ...
    def assign(self, identity: ApplicationIdentity, *, read: Sequence[str], publish: Sequence[str]) -> None: ...
    def resolve(self, identity: ApplicationIdentity) -> KeySet: ...

class PolicyRequest:
    def __init__(self, object_type: str, use_context: UseContext) -> None: ...
    @property
    def object_type(self) -> str: ...
    @property
    def use_context(self) -> UseContext: ...
class WorkflowRequest:
    def __init__(self, input: UseContext, output: UseContext) -> None: ...
    @property
    def input(self) -> UseContext: ...
    @property
    def output(self) -> UseContext: ...
class InputRule:
    def __init__(self, groups: Sequence[str], *, object_type: str | None = ...) -> None: ...
    @property
    def groups(self) -> list[str]: ...
    @property
    def object_type(self) -> str | None: ...
class WorkflowPolicy:
    def __init__(self, inputs: Sequence[InputRule], output_type: str, destination: str) -> None: ...
    @property
    def inputs(self) -> list[InputRule]: ...
    @property
    def output_type(self) -> str: ...
    @property
    def destination(self) -> str: ...
class GovernanceProvider(Protocol):
    def policy(self, request: PolicyRequest) -> Governance: ...
    def workflow(self, request: WorkflowRequest) -> WorkflowPolicy: ...
    def accept(self, context: AdmissionContext) -> bool: ...
    def attach(self, context: AttachmentContext) -> bool: ...
    def release(self, context: ReleaseContext) -> bool: ...
class PolicyDirectory:
    def __init__(self) -> None: ...
    def trust(self, identity: ApplicationIdentity) -> None: ...
    def add_policy(self, request: PolicyRequest, policy: Governance) -> None: ...
    def approve_contract(self, request: PolicyRequest, policy: Governance) -> None: ...
    def add_workflow(self, request: WorkflowRequest, policy: WorkflowPolicy) -> None: ...
    def policy(self, request: PolicyRequest) -> Governance: ...
    def workflow(self, request: WorkflowRequest) -> WorkflowPolicy: ...
    def accept(self, context: AdmissionContext) -> bool: ...
    def attach(self, context: AttachmentContext) -> bool: ...
    def release(self, context: ReleaseContext) -> bool: ...

class CatalogRequest:
    def __init__(self, dataset: str, edition: str, use_context: UseContext) -> None: ...
    @property
    def dataset(self) -> str: ...
    @property
    def edition(self) -> str: ...
    @property
    def use_context(self) -> UseContext: ...
class CatalogEntry:
    def __init__(self, publication: GovernedObject, selection: DatasetSelection) -> None: ...
    @property
    def publication(self) -> GovernedObject: ...
    @property
    def selection(self) -> DatasetSelection: ...
class CatalogProvider(Protocol):
    def resolve(self, request: CatalogRequest) -> CatalogEntry: ...
class EditionCatalog:
    def __init__(self) -> None: ...
    def insert(self, entry: CatalogEntry) -> None: ...
    def resolve(self, request: CatalogRequest) -> CatalogEntry: ...

class RegisterEvent:
    @property
    def action(self) -> str: ...
    @property
    def publication(self) -> GovernedObject: ...
    @property
    def purpose(self) -> str: ...
    @property
    def destination(self) -> str: ...
    @property
    def policy_refs(self) -> list[str]: ...
class RegisterProvider(Protocol):
    def record(self, event: RegisterEvent) -> None: ...
class FileRegisters:
    def __init__(self, registers: ObjectRegisters) -> None: ...

class Providers:
    def __init__(self, identity: IdentityProvider, keys: KeyProvider,
                 governance: GovernanceProvider, *, catalog: CatalogProvider | None = ...,
                 registers: RegisterProvider | FileRegisters | None = ...) -> None: ...
    def session(self, application: str, *, workflows: Sequence[WorkflowRequest]) -> Session: ...
    def policy(self, request: PolicyRequest) -> Governance: ...
    def resolve(self, request: CatalogRequest) -> CatalogEntry: ...


class FileKeyStore:
    @staticmethod
    def create(path: str | PathLike[str], application: str, groups: Sequence[str], *, cipher: str = ...) -> FileKeyStore: ...
    @staticmethod
    def open(path: str | PathLike[str]) -> FileKeyStore: ...
    @overload
    def resolve(self, request: str) -> ApplicationIdentity: ...
    @overload
    def resolve(self, request: ApplicationIdentity) -> KeySet: ...
    @property
    def application(self) -> str: ...
    @property
    def cipher(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def groups(self) -> list[str]: ...
