"""Typed governance provider contract. Protocol operations execute in Rust."""
from typing import Protocol
from tn._native.governed import PolicyRequest, WorkflowRequest, InputRule, WorkflowPolicy, PolicyDirectory, Governance, AdmissionContext, AttachmentContext, ReleaseContext

class GovernanceProvider(Protocol):
    def policy(self, request: PolicyRequest) -> Governance: ...
    def workflow(self, request: WorkflowRequest) -> WorkflowPolicy: ...
    def accept(self, context: AdmissionContext) -> bool: ...
    def attach(self, context: AttachmentContext) -> bool: ...
    def release(self, context: ReleaseContext) -> bool: ...
