from collections.abc import Callable, MutableMapping, MutableSequence, Sequence
from os import PathLike
from types import TracebackType
from typing import ClassVar, NoReturn, TypeAlias

_Json: TypeAlias = None | bool | int | float | str | list["_Json"] | dict[str, "_Json"]
_JsonInput: TypeAlias = (
    None
    | bool
    | int
    | float
    | str
    | list["_JsonInput"]
    | tuple["_JsonInput", ...]
    | dict[str, "_JsonInput"]
)
_MutableJson: TypeAlias = (
    None
    | bool
    | int
    | float
    | str
    | MutableSequence["_MutableJson"]
    | MutableMapping[str, "_MutableJson"]
)

class GovernedError(Exception): ...
class NotEntitled(GovernedError): ...
class NotAPublisher(GovernedError): ...
class UseDenied(GovernedError): ...
class VerificationError(GovernedError): ...
class SessionClosed(GovernedError): ...

class UseContext:
    """Immutable native application, purpose and operation tuple."""
    def __init__(self, application: str, purpose: str, operation: str) -> None: ...
    @property
    def application(self) -> str: ...
    @property
    def purpose(self) -> str: ...
    @property
    def operation(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class Governance:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def from_markdown(
        governed_by: str, markdown: str, policy_id: str, object_type: str
    ) -> Governance: ...
    @property
    def governed_by(self) -> str: ...
    @property
    def policy_ref(self) -> str: ...
    @property
    def fields(self) -> dict[str, _Json]: ...
    def get(self, name: str) -> _Json: ...
    def matches_contract(self, expected: Governance) -> bool: ...
    @property
    def revision_id(self) -> str | None: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def dataset_bindings(self) -> list[DatasetBinding]: ...

class SourceReference:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_id(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def governed_by(self) -> str: ...
    @property
    def policy_ref(self) -> str: ...
    @property
    def revision_id(self) -> str | None: ...
    @property
    def groups(self) -> list[str]: ...
    @property
    def operation(self) -> str: ...
    def references(self, object: GovernedObject) -> bool: ...
    def references_with_policy(self, object: GovernedObject, accepted_policy: Governance) -> bool: ...

class DataState:
    """Owned decision snapshot; returned dictionaries are detached copies."""
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_type(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def dataset_bindings(self) -> list[DatasetBinding]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def groups(self) -> dict[str, dict[str, _Json]]: ...
    @property
    def snapshot(self) -> GovernedObject | None: ...
    @property
    def revision(self) -> int: ...
    @property
    def has_unreleased_changes(self) -> bool: ...
    @property
    def hidden_groups(self) -> list[str]: ...

class AdmissionContext:
    """Owned snapshot of an authenticated native admission callback."""
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object(self) -> GovernedObject: ...
    @property
    def writer(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def operation(self) -> str: ...
    @property
    def purpose(self) -> str: ...
    @property
    def use_context(self) -> UseContext | None: ...
    @property
    def groups(self) -> list[str] | None: ...

class AttachmentContext:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def authority(self) -> str: ...
    @property
    def data(self) -> DataState: ...
    @property
    def policy(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...

class ReleaseContext:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def writer(self) -> str: ...
    @property
    def data(self) -> DataState: ...
    @property
    def object_type(self) -> str: ...
    @property
    def purpose(self) -> str: ...
    @property
    def use_context(self) -> UseContext | None: ...
    @property
    def destination(self) -> str: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...

class PublicationReport:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def required_groups(self) -> list[str]: ...
    @property
    def supported_groups(self) -> list[str]: ...
    @property
    def missing_groups(self) -> list[str]: ...
    @property
    def unavailable_groups(self) -> list[str]: ...
    @property
    def unknown_groups(self) -> list[str]: ...
    @property
    def is_ready(self) -> bool: ...

class DataObject:
    def __init__(self, _native: NoReturn) -> None: ...
    def copy(self) -> DataObject: ...
    @property
    def object_type(self) -> str: ...
    @property
    def data(self) -> MutableMapping[str, _MutableJson]: ...
    @property
    def groups(self) -> MutableMapping[str, MutableMapping[str, _MutableJson]]: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def dataset_bindings(self) -> list[DatasetBinding]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def hidden_groups(self) -> list[str]: ...
    @property
    def snapshot(self) -> GovernedObject: ...
    @property
    def history(self) -> list[GovernedObject]: ...
    @property
    def state(self) -> DataState: ...
    @property
    def revision(self) -> int: ...
    @property
    def has_unreleased_changes(self) -> bool: ...
    @property
    def register_error(self) -> str | None: ...
    def attach(
        self, policy: Governance, *, decide: Callable[[AttachmentContext], bool]
    ) -> None: ...
    def include(self, other: DataObject) -> None: ...
    def retain_groups(self, groups: Sequence[str]) -> None: ...
    def release(
        self,
        *,
        to: str,
        decide: Callable[[ReleaseContext], bool],
        purpose: str | None = None,
        use: UseContext | None = None,
        object_type: str | None = None,
    ) -> GovernedObject: ...

class GovernedDraft:
    def __init__(self, object_type: str, governance: Governance) -> None: ...
    def group(self, name: str, fields: dict[str, _JsonInput]) -> GovernedDraft: ...
    @property
    def governance(self) -> Governance: ...

class GovernedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def parse(wire: str | bytes) -> GovernedObject: ...
    @property
    def wire(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def group_names(self) -> list[str]: ...
    @property
    def envelope(self) -> dict[str, _Json]: ...
    def __str__(self) -> str: ...
    def __bytes__(self) -> bytes: ...

class GovernanceView:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...
    def accept(
        self, *, use: UseContext, groups: Sequence[str], decide: Callable[[AdmissionContext], bool]
    ) -> AdmittedObject: ...
    def authorize(
        self, operation: str, decision: Callable[[Governance, str], bool]
    ) -> AdmittedObject: ...

class AdmittedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def operation(self) -> str: ...
    @property
    def use_context(self) -> UseContext | None: ...
    @property
    def selected_groups(self) -> list[str] | None: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...

class OpenedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def use_context(self) -> UseContext | None: ...
    @property
    def groups(self) -> dict[str, dict[str, _Json]]: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...
    @property
    def hidden_groups(self) -> list[str]: ...
    def derive(self, object_type: str) -> GovernedDraft: ...
    def derive_under(self, object_type: str, governance: Governance) -> GovernedDraft: ...

class GovernedReader:
    def __init__(self, _native: NoReturn) -> None: ...
    def governance(self, object: GovernedObject) -> GovernanceView: ...
    def open(self, admitted: AdmittedObject, groups: Sequence[str]) -> OpenedObject: ...

class Session:
    def __init__(
        self, policy: str, *, groups: Sequence[str] | None = None, policy_id: str = "agents.md"
    ) -> None: ...
    @staticmethod
    def from_config(path: str | PathLike[str]) -> Session: ...
    def create_obj(
        self,
        fields: dict[str, _JsonInput],
        policy: Governance,
        *,
        object_type: str,
        group: str = "default",
    ) -> DataObject: ...
    def create_obj_with_groups(
        self,
        groups: dict[str, dict[str, _JsonInput]],
        policy: Governance,
        *,
        object_type: str,
        primary_group: str = "default",
    ) -> DataObject: ...
    def receive(
        self,
        sealed: str | bytes | GovernedObject,
        *,
        decide: Callable[[AdmissionContext], bool],
        purpose: str | None = None,
        use: UseContext | None = None,
        groups: Sequence[str] | None = None,
        selection: DatasetSelection | None = None,
    ) -> DataObject: ...
    def check_groups(self, groups: Sequence[str]) -> PublicationReport: ...
    def release(
        self,
        data: DataObject,
        *,
        use: UseContext,
        to: str,
        decide: Callable[[ReleaseContext], bool],
        object_type: str | None = None,
    ) -> GovernedObject: ...
    def require_groups(self, groups: Sequence[str]) -> None: ...
    @property
    def did(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def draft(self, object_type: str, *, governance: Governance | None = None) -> GovernedDraft: ...
    def policy(self, object_type: str) -> Governance: ...
    def seal(self, draft: GovernedDraft) -> GovernedObject: ...
    def verify(self, wire: str | bytes) -> GovernedObject: ...
    def reader(self, *, groups: Sequence[str] | None = None) -> GovernedReader: ...
    def governance(self, object: GovernedObject) -> GovernanceView: ...
    def open(self, admitted: AdmittedObject, groups: Sequence[str]) -> OpenedObject: ...

class PolicyRelation:
    def __init__(self, _native: NoReturn) -> None: ...
    Revise: ClassVar[PolicyRelation]
    Extend: ClassVar[PolicyRelation]
    Combine: ClassVar[PolicyRelation]
    def __eq__(self, other: object) -> bool: ...

class PolicyParent:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def revision_id(self) -> str: ...
    @property
    def relation(self) -> PolicyRelation: ...

class PolicyRevisionDraft:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def from_markdown(
        authority: str, markdown: str, policy_id: str, event_type: str, scope: str
    ) -> PolicyRevisionDraft: ...
    def parent(self, revision_id: str, relation: PolicyRelation) -> PolicyRevisionDraft: ...
    def into_draft(self, administration_contract: Governance) -> GovernedDraft: ...

class PolicyRevision:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def from_opened(opened: OpenedObject) -> PolicyRevision: ...
    @property
    def id(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def scope(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def parents(self) -> list[PolicyParent]: ...
    @property
    def object(self) -> GovernedObject: ...

class PolicyDag:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def get(self, revision_id: str) -> PolicyRevision | None: ...
    def admit(
        self,
        revision: PolicyRevision,
        authorize: Callable[[PolicyRevision, tuple[PolicyParent, PolicyRevision] | None], bool],
    ) -> None: ...
    def select(
        self, revision_id: str, scope: str, applicable: Callable[[PolicyRevision], bool]
    ) -> Governance: ...
    def resolve(self, governance: Governance, scope: str) -> PolicyRevision: ...

class ContractBinding:
    def __init__(self, revision_id: str, scope: str) -> None: ...
    @property
    def revision_id(self) -> str: ...
    @property
    def scope(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class EvaluatorArtifactSet:
    def __init__(
        self,
        policy_revision: str,
        compiled_policy_sha256: str,
        profile_sha256: str,
        wasm_sha256: str,
        data_sha256: str,
    ) -> None: ...
    @property
    def policy_revision(self) -> str: ...
    @property
    def compiled_policy_sha256(self) -> str: ...
    @property
    def profile_sha256(self) -> str: ...
    @property
    def wasm_sha256(self) -> str: ...
    @property
    def data_sha256(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class DatasetBinding:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def dataset(self) -> str: ...
    @property
    def edition(self) -> str: ...
    @property
    def source_object_id(self) -> str: ...
    @property
    def edition_record_id(self) -> str: ...
    @property
    def contracts(self) -> list[ContractBinding]: ...
    @property
    def fields(self) -> dict[str, _Json]: ...
    def __eq__(self, other: object) -> bool: ...

class DatasetEditionDraft:
    def __init__(
        self,
        dataset: str,
        edition: str,
        source: GovernedObject,
        source_groups: Sequence[str],
        contracts: Sequence[ContractBinding],
        eligible_uses: Sequence[UseContext],
        grant_ref: str,
        evaluator_artifacts: Sequence[EvaluatorArtifactSet],
    ) -> None: ...
    def into_draft(self, administration_contract: Governance) -> GovernedDraft: ...

class DatasetEdition:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def from_opened(opened: OpenedObject) -> DatasetEdition: ...
    @property
    def id(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def dataset(self) -> str: ...
    @property
    def edition(self) -> str: ...
    @property
    def source_object_id(self) -> str: ...
    @property
    def source_writer(self) -> str: ...
    @property
    def source_type(self) -> str: ...
    @property
    def source_groups(self) -> list[str]: ...
    @property
    def contracts(self) -> list[ContractBinding]: ...
    @property
    def eligible_uses(self) -> list[UseContext]: ...
    @property
    def grant_ref(self) -> str: ...
    @property
    def evaluator_artifacts(self) -> list[EvaluatorArtifactSet]: ...
    @property
    def object(self) -> GovernedObject: ...

class DatasetCatalog:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def get(self, record_id: str) -> DatasetEdition | None: ...
    def admit(
        self, edition: DatasetEdition, dag: PolicyDag, authorize: Callable[[DatasetEdition], bool]
    ) -> None: ...
    def select(
        self, dataset: str, edition: str, record_id: str, use_context: UseContext
    ) -> DatasetSelection: ...
    def verify_binding(self, binding: DatasetBinding, dag: PolicyDag) -> None: ...
    def accepts(self, context: AdmissionContext, dag: PolicyDag) -> bool: ...

class DatasetSelection:
    """Accepted native selection; arbitrary dictionaries cannot construct it."""
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def record(self) -> DatasetEdition: ...
    @property
    def use_context(self) -> UseContext: ...
    @property
    def binding(self) -> DatasetBinding: ...
    @property
    def dataset(self) -> str: ...
    @property
    def edition(self) -> str: ...
    @property
    def source_object_id(self) -> str: ...
    @property
    def edition_record_id(self) -> str: ...
    def verify_source(
        self, view: GovernanceView, use_context: UseContext, groups: Sequence[str]
    ) -> None: ...

class VerifiedLineage:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_ids(self) -> list[str]: ...
    @property
    def source_object_ids(self) -> list[str]: ...

class LineageVerifier:
    def __init__(self, *, max_objects: int = 1024, max_depth: int = 64) -> None: ...
    def verify(
        self,
        view: GovernanceView,
        catalog: DatasetCatalog,
        dag: PolicyDag,
        resolve: Callable[[str], GovernanceView],
    ) -> VerifiedLineage: ...
