from collections.abc import Callable, MutableMapping, MutableSequence, Sequence
from os import PathLike
from types import TracebackType
from typing import NoReturn, TypeAlias

_Json: TypeAlias = None | bool | int | float | str | list["_Json"] | dict[str, "_Json"]
_JsonInput: TypeAlias = (
    None
    | bool
    | int
    | float
    | str
    | list["_JsonInput"]
    | tuple["_JsonInput", ...]
    | dict[str, "_JsonInput"]
)
_MutableJson: TypeAlias = (
    None
    | bool
    | int
    | float
    | str
    | MutableSequence["_MutableJson"]
    | MutableMapping[str, "_MutableJson"]
)

class GovernedError(Exception): ...
class NotEntitled(GovernedError): ...
class NotAPublisher(GovernedError): ...
class UseDenied(GovernedError): ...
class VerificationError(GovernedError): ...
class SessionClosed(GovernedError): ...

class Governance:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def from_markdown(
        governed_by: str, markdown: str, policy_id: str, object_type: str
    ) -> Governance: ...
    @property
    def governed_by(self) -> str: ...
    @property
    def policy_ref(self) -> str: ...
    @property
    def fields(self) -> dict[str, _Json]: ...
    def get(self, name: str) -> _Json: ...
    def matches_contract(self, expected: Governance) -> bool: ...
    @property
    def revision_id(self) -> str | None: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...

class SourceReference:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_id(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def governed_by(self) -> str: ...
    @property
    def policy_ref(self) -> str: ...
    @property
    def revision_id(self) -> str | None: ...
    @property
    def groups(self) -> list[str]: ...
    @property
    def operation(self) -> str: ...
    def references(self, object: GovernedObject) -> bool: ...

class DataState:
    """Owned decision snapshot; returned dictionaries are detached copies."""
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_type(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def groups(self) -> dict[str, dict[str, _Json]]: ...
    @property
    def snapshot(self) -> GovernedObject | None: ...
    @property
    def revision(self) -> int: ...

class AdmissionContext:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object(self) -> GovernedObject: ...
    @property
    def writer(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def operation(self) -> str: ...
    @property
    def purpose(self) -> str: ...

class AttachmentContext:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def authority(self) -> str: ...
    @property
    def data(self) -> DataState: ...
    @property
    def policy(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...

class ReleaseContext:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def writer(self) -> str: ...
    @property
    def data(self) -> DataState: ...
    @property
    def object_type(self) -> str: ...
    @property
    def purpose(self) -> str: ...
    @property
    def destination(self) -> str: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...

class PublicationReport:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def required_groups(self) -> list[str]: ...
    @property
    def supported_groups(self) -> list[str]: ...
    @property
    def missing_groups(self) -> list[str]: ...
    @property
    def unavailable_groups(self) -> list[str]: ...
    @property
    def unknown_groups(self) -> list[str]: ...
    @property
    def is_ready(self) -> bool: ...

class DataObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def object_type(self) -> str: ...
    @property
    def data(self) -> MutableMapping[str, _MutableJson]: ...
    @property
    def groups(self) -> MutableMapping[str, MutableMapping[str, _MutableJson]]: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def policies(self) -> list[Governance]: ...
    @property
    def sources(self) -> list[SourceReference]: ...
    @property
    def hidden_groups(self) -> list[str]: ...
    @property
    def snapshot(self) -> GovernedObject: ...
    @property
    def history(self) -> list[GovernedObject]: ...
    @property
    def state(self) -> DataState: ...
    @property
    def revision(self) -> int: ...
    @property
    def register_error(self) -> str | None: ...
    def attach(
        self, policy: Governance, *, decide: Callable[[AttachmentContext], bool]
    ) -> None: ...
    def include(self, other: DataObject) -> None: ...
    def release(
        self,
        *,
        to: str,
        purpose: str,
        decide: Callable[[ReleaseContext], bool],
        object_type: str | None = None,
    ) -> GovernedObject: ...

class GovernedDraft:
    def __init__(self, object_type: str, governance: Governance) -> None: ...
    def group(self, name: str, fields: dict[str, _JsonInput]) -> GovernedDraft: ...
    @property
    def governance(self) -> Governance: ...

class GovernedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @staticmethod
    def parse(wire: str | bytes) -> GovernedObject: ...
    @property
    def wire(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def writer(self) -> str: ...
    @property
    def object_type(self) -> str: ...
    @property
    def group_names(self) -> list[str]: ...
    @property
    def envelope(self) -> dict[str, _Json]: ...
    def __str__(self) -> str: ...
    def __bytes__(self) -> bytes: ...

class GovernanceView:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...
    def authorize(
        self, operation: str, decision: Callable[[Governance, str], bool]
    ) -> AdmittedObject: ...

class AdmittedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def operation(self) -> str: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...

class OpenedObject:
    def __init__(self, _native: NoReturn) -> None: ...
    @property
    def groups(self) -> dict[str, dict[str, _Json]]: ...
    @property
    def governance(self) -> Governance: ...
    @property
    def object(self) -> GovernedObject: ...
    @property
    def hidden_groups(self) -> list[str]: ...
    def derive(self, object_type: str) -> GovernedDraft: ...
    def derive_under(self, object_type: str, governance: Governance) -> GovernedDraft: ...

class GovernedReader:
    def __init__(self, _native: NoReturn) -> None: ...
    def governance(self, object: GovernedObject) -> GovernanceView: ...
    def open(self, admitted: AdmittedObject, groups: Sequence[str]) -> OpenedObject: ...

class Session:
    def __init__(
        self, policy: str, *, groups: Sequence[str] | None = None, policy_id: str = "agents.md"
    ) -> None: ...
    @staticmethod
    def from_config(path: str | PathLike[str]) -> Session: ...
    def create_obj(
        self,
        fields: dict[str, _JsonInput],
        policy: Governance,
        *,
        object_type: str,
        group: str = "default",
    ) -> DataObject: ...
    def receive(
        self,
        sealed: str | bytes | GovernedObject,
        *,
        purpose: str,
        decide: Callable[[AdmissionContext], bool],
        groups: Sequence[str] | None = None,
    ) -> DataObject: ...
    def check_groups(self, groups: Sequence[str]) -> PublicationReport: ...
    def require_groups(self, groups: Sequence[str]) -> None: ...
    @property
    def did(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def draft(self, object_type: str, *, governance: Governance | None = None) -> GovernedDraft: ...
    def policy(self, object_type: str) -> Governance: ...
    def seal(self, draft: GovernedDraft) -> GovernedObject: ...
    def verify(self, wire: str | bytes) -> GovernedObject: ...
    def reader(self, *, groups: Sequence[str] | None = None) -> GovernedReader: ...
    def governance(self, object: GovernedObject) -> GovernanceView: ...
    def open(self, admitted: AdmittedObject, groups: Sequence[str]) -> OpenedObject: ...
