"""Governed data objects and independent Rust-backed session instances.

Create a Session from policy text or use Session.from_config(path). Each
instance owns its context; calls never select a module-global runtime.
"""

from tn._native.governed import (
    AdmissionContext,
    AdmittedObject,
    AttachmentContext,
    ContractBinding,
    DataObject,
    DataState,
    DatasetBinding,
    DatasetCatalog,
    DatasetEdition,
    DatasetEditionDraft,
    DatasetSelection,
    EvaluatorArtifactSet,
    Governance,
    GovernanceView,
    GovernedDraft,
    GovernedError,
    GovernedObject,
    GovernedReader,
    LineageVerifier,
    NotAPublisher,
    NotEntitled,
    OpenedObject,
    PolicyDag,
    PolicyParent,
    PolicyRelation,
    PolicyRevision,
    PolicyRevisionDraft,
    PublicationReport,
    ReleaseContext,
    Session,
    SessionClosed,
    SourceReference,
    UseContext,
    UseDenied,
    VerificationError,
    VerifiedLineage,
)

__all__ = [
    "AdmissionContext",
    "AdmittedObject",
    "AttachmentContext",
    "ContractBinding",
    "DataObject",
    "DataState",
    "DatasetBinding",
    "DatasetCatalog",
    "DatasetEdition",
    "DatasetEditionDraft",
    "DatasetSelection",
    "EvaluatorArtifactSet",
    "Governance",
    "GovernanceView",
    "GovernedDraft",
    "GovernedError",
    "GovernedObject",
    "GovernedReader",
    "LineageVerifier",
    "NotAPublisher",
    "NotEntitled",
    "OpenedObject",
    "PolicyDag",
    "PolicyParent",
    "PolicyRelation",
    "PolicyRevision",
    "PolicyRevisionDraft",
    "PublicationReport",
    "ReleaseContext",
    "Session",
    "SessionClosed",
    "SourceReference",
    "UseContext",
    "UseDenied",
    "VerificationError",
    "VerifiedLineage",
]
