// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.
// Run `npm run gen:version` (or any build/test) to regenerate.

export const SDK_VERSION = "0.6.11";

/** User-Agent for every outbound HTTP call the SDK makes (vault, account,
 * wallet, bootstrap). Mirrors Python's dynamic `tn-proto/<version>`. */
export const USER_AGENT = `tn-proto-ts/${SDK_VERSION}`;
