// Cross-language absorb vault-metadata-adoption contract (TS side).
//
// Consumes the shared golden ../../tests/fixtures/absorb/vault_adoption_cases.json
// (generated by python/tools/generate_absorb_vault_adoption_fixture.py) and
// proves the TS project-seed vault-adoption patch matches the Python
// reference on every case. The Python side asserts the same cases in
// python/tests/test_absorb_vault_adoption_contract.py.
//
// The two implementations serialize YAML differently, so the golden
// records the semantic outcome (changed?, vaultOnly?, resulting vault
// fields) rather than raw patched bytes.

import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { parse as parseYaml } from "yaml";

import { _projectSeedVaultYamlPatch } from "../src/runtime/absorb_bootstrap.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(HERE, "..", "..", "tests", "fixtures", "absorb", "vault_adoption_cases.json");

interface ExpectedResult {
  url: string;
  linked_project_id: string;
  enabled: boolean | null;
}
interface Case {
  name: string;
  existing_yaml: string;
  incoming_yaml: string;
  expected: { changed: boolean; vault_only: boolean; result: ExpectedResult | null };
}

const cases = (JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as { cases: Case[] }).cases;

for (const c of cases) {
  test(`absorb vault adoption: ${c.name}`, () => {
    const enc = new TextEncoder();
    const { patched, vaultOnly } = _projectSeedVaultYamlPatch(
      enc.encode(c.existing_yaml),
      enc.encode(c.incoming_yaml),
    );

    assert.equal(patched !== undefined, c.expected.changed, "changed mismatch");
    assert.equal(vaultOnly, c.expected.vault_only, "vaultOnly mismatch");

    const effective = patched ? new TextDecoder().decode(patched) : c.existing_yaml;
    const doc = (parseYaml(effective) ?? {}) as Record<string, unknown>;
    const vault = doc["vault"] as Record<string, unknown> | undefined;

    if (c.expected.result === null) {
      assert.equal(vault === undefined || vault === null || typeof vault !== "object", true,
        "expected no vault block");
      return;
    }

    assert.ok(vault && typeof vault === "object", "expected a vault block");
    assert.equal((vault["url"] as string) ?? "", c.expected.result.url);
    assert.equal((vault["linked_project_id"] as string) ?? "", c.expected.result.linked_project_id);
    assert.equal((vault["enabled"] as boolean | undefined) ?? null, c.expected.result.enabled);
  });
}
