import { test } from "node:test";
import { strict as assert } from "node:assert";
import { createDecipheriv } from "node:crypto";
import { Buffer } from "node:buffer";

import {
  stubBek,
  firehoseWsUrl,
  encryptFirehoseFrame,
  TnFirehoseHandler,
} from "../src/handlers/firehose.js";

// Cross-SDK parity with python/tn/handlers/firehose.py. The wire frame
// (stub BEK + AAD + nonce||ct+tag) must be byte-identical so a TS-encrypted
// frame decrypts under the Python handler's key and vice versa.

const PROJECT = "00000000-0000-0000-0000-000000000000";

test("stubBek matches Python _stub_bek byte-for-byte", () => {
  // Fixture computed by python/tn/handlers/firehose.py::_stub_bek.
  const expectedHex = "24df69ab492c5b0da51c3be43232a5e30a58c78c5121cd966002a55ee9f41697";
  assert.equal(Buffer.from(stubBek(PROJECT, null)).toString("hex"), expectedHex);
});

test("firehoseWsUrl maps https->wss and appends /firehose/<project>", () => {
  assert.equal(
    firehoseWsUrl("https://vault.tn-proto.org", PROJECT),
    `wss://vault.tn-proto.org/firehose/${PROJECT}`,
  );
  assert.equal(
    firehoseWsUrl("http://localhost:38790", PROJECT),
    `ws://localhost:38790/firehose/${PROJECT}`,
  );
});

test("encryptFirehoseFrame is byte-identical to Python (fixed nonce vector)", () => {
  // Vector generated by the Python firehose crypto with nonce 00..0b.
  const bek = stubBek(PROJECT, null);
  const nonce = Uint8Array.from(Array.from({ length: 12 }, (_, i) => i));
  const rawLine = new TextEncoder().encode('{"event_type":"tn.test.frame","x":1}\n');
  const wire = encryptFirehoseFrame(bek, PROJECT, null, "tn.test.frame", rawLine, nonce);
  const expectedWireHex =
    "000102030405060708090a0b3bab6875768b41368f85144bb4026e5fcfc4d40f526a3efb7810df3ad4e8fb13e006cf6b650d3dcf715de832a868b05dd8f7090256";
  assert.equal(Buffer.from(wire).toString("hex"), expectedWireHex);
});

test("a TS-encrypted frame round-trips under the same BEK + AAD", () => {
  const bek = stubBek(PROJECT, null);
  const rawLine = new TextEncoder().encode('{"event_type":"tn.demo","n":42}\n');
  const wire = encryptFirehoseFrame(bek, PROJECT, null, "tn.demo", rawLine);

  // Decrypt the way the consumer would: split nonce(12) || ct || tag(16).
  const nonce = wire.subarray(0, 12);
  const body = wire.subarray(12);
  const ct = body.subarray(0, body.length - 16);
  const tag = body.subarray(body.length - 16);
  const aad = Buffer.from(`${PROJECT}|stub|tn.demo`, "utf-8");
  const decipher = createDecipheriv("aes-256-gcm", Buffer.from(bek), Buffer.from(nonce));
  decipher.setAAD(aad);
  decipher.setAuthTag(Buffer.from(tag));
  const out = Buffer.concat([decipher.update(Buffer.from(ct)), decipher.final()]);
  assert.equal(out.toString("utf-8"), '{"event_type":"tn.demo","n":42}\n');
});

test("wrong AAD (event_type swap) fails the auth tag", () => {
  const bek = stubBek(PROJECT, null);
  const wire = encryptFirehoseFrame(bek, PROJECT, null, "tn.real", new TextEncoder().encode("x"));
  const nonce = wire.subarray(0, 12);
  const body = wire.subarray(12);
  const ct = body.subarray(0, body.length - 16);
  const tag = body.subarray(body.length - 16);
  const wrongAad = Buffer.from(`${PROJECT}|stub|tn.SPOOFED`, "utf-8");
  const decipher = createDecipheriv("aes-256-gcm", Buffer.from(bek), Buffer.from(nonce));
  decipher.setAAD(wrongAad);
  decipher.setAuthTag(Buffer.from(tag));
  assert.throws(() => Buffer.concat([decipher.update(Buffer.from(ct)), decipher.final()]));
});

test("constructor validates endpoint, project_id, key_id", () => {
  assert.throws(() => new TnFirehoseHandler("fh", { endpoint: "ftp://x", projectId: PROJECT }), /http/);
  assert.throws(() => new TnFirehoseHandler("fh", { endpoint: "https://v", projectId: "not-a-uuid" }), /project_id/);
  assert.throws(
    () => new TnFirehoseHandler("fh", { endpoint: "https://v", projectId: PROJECT, keyId: "badkey" }),
    /key_id/,
  );
  // Valid construction does not throw.
  const h = new TnFirehoseHandler("fh", { endpoint: "https://v", projectId: PROJECT, keyId: "fhk_abc234" });
  assert.equal(h.resolved_address(), `wss://v/firehose/${PROJECT}`);
});

test("filter gates which envelopes reach emit (accepts)", () => {
  const h = new TnFirehoseHandler("fh", {
    endpoint: "https://v",
    projectId: PROJECT,
    filter: { levelIn: ["warning", "error"] },
  });
  assert.equal(h.accepts({ event_type: "x", level: "info" }), false);
  assert.equal(h.accepts({ event_type: "x", level: "error" }), true);
});
