// Cross-language byte-interop + round-trip tests for the TS port of
// the recipient_wrap sealed-box scheme.
//
// The byte-interop test loads a Python-produced fixture
// (test/fixtures/recipient_seal_fixture.json, generated by
// build_recipient_seal_fixture.py) and unseals it in TS. A passing
// unseal proves every wire-format choice — HKDF salt order, ed25519->
// x25519 birational map, base58btc multibase + multicodec parsing,
// AES-GCM tag layout, base64 padding, the AAD strip list — matches
// the Python reference byte-for-byte.

import { strict as assert } from "node:assert";
import { Buffer } from "node:buffer";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import {
  WRAP_FRAME,
  UnsealError,
  manifestAadForWrap,
  sealBekForRecipient,
  unsealBekFromWrap,
  didKeyToEd25519Pub,
  type RecipientWrap,
} from "../src/core/recipient_seal.js";
import { canonicalize } from "../src/core/canonical.js";
import { DeviceKey } from "../src/core/signing.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(HERE, "fixtures", "recipient_seal_fixture.json");

function hexToBytes(s: string): Uint8Array {
  if (s.length % 2 !== 0) throw new Error("hex string odd length");
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(b: Uint8Array): string {
  return Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
}

interface SealFixture {
  ed25519_seed_hex: string;
  recipient_did: string;
  bek_hex: string;
  manifest: Record<string, unknown>;
  wrap: RecipientWrap;
}

function loadFixture(): SealFixture {
  return JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as SealFixture;
}

// ── byte-interop: TS unseals Python's fixture ──────────────────────

test("recipient_seal: TS unseal of Python-produced wrap recovers BEK", async () => {
  const f = loadFixture();
  const seed = hexToBytes(f.ed25519_seed_hex);
  const expectedBek = hexToBytes(f.bek_hex);

  // recipient_did derived in JS must match Python's so the test fails
  // loudly on a base58btc / multicodec drift before the seal path runs.
  const dk = DeviceKey.fromSeed(seed);
  assert.equal(dk.did, f.recipient_did);

  const aad = manifestAadForWrap(f.manifest);
  // Sanity-check AAD length matches the producer's record (Python
  // included _aad_len in the fixture for exactly this reason).
  const aadLen = (f as unknown as { _aad_len: number })._aad_len;
  assert.equal(aad.length, aadLen);

  const bek = await unsealBekFromWrap(f.wrap, seed, aad);
  assert.equal(bytesToHex(bek), bytesToHex(expectedBek));
});

// ── manifestAadForWrap: strips the right keys ──────────────────────

test("manifestAadForWrap: strips signature + recipient_wrap + recipient_wraps", () => {
  const m = {
    kind: "kit_bundle",
    state: {
      body_encryption: {
        alg: "AES-256-GCM",
        recipient_wrap: { frame: "tn-sealed-box-v1" },
        recipient_wraps: [{ frame: "tn-sealed-box-v1" }],
      },
    },
    manifest_signature_b64: "STALE",
  };
  const aad = manifestAadForWrap(m);
  const text = Buffer.from(aad).toString("utf-8");
  assert.equal(text.includes("manifest_signature_b64"), false);
  assert.equal(text.includes("recipient_wrap"), false);
  assert.equal(text.includes("STALE"), false);
  // alg is bound (not stripped).
  assert.equal(text.includes("AES-256-GCM"), true);
});

test("manifestAadForWrap: does not mutate caller's manifest", () => {
  const m = {
    kind: "kit_bundle",
    state: {
      body_encryption: {
        recipient_wraps: [{ frame: "tn-sealed-box-v1" }],
      },
    },
    manifest_signature_b64: "STALE",
  };
  const before = canonicalize(m);
  manifestAadForWrap(m);
  const after = canonicalize(m);
  assert.deepEqual(Array.from(before), Array.from(after));
});

// ── seal+unseal round-trip in TS ───────────────────────────────────

test("seal/unseal round-trip in TS recovers the BEK", async () => {
  const seed = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) seed[i] = i + 1;
  const dk = DeviceKey.fromSeed(seed);

  const bek = new Uint8Array(32);
  globalThis.crypto.getRandomValues(bek);

  const manifest = {
    kind: "kit_bundle",
    to_did: dk.did,
    state: { body_encryption: { alg: "AES-256-GCM" } },
  };
  const aad = manifestAadForWrap(manifest);

  const wrap = await sealBekForRecipient(bek, dk.did, aad);
  assert.equal(wrap.frame, WRAP_FRAME);
  assert.equal(wrap.recipient_did, dk.did);
  assert.equal(typeof wrap.ephemeral_x25519_pub_b64, "string");
  assert.equal(typeof wrap.wrap_nonce_b64, "string");
  assert.equal(typeof wrap.wrapped_bek_b64, "string");

  const recovered = await unsealBekFromWrap(wrap, seed, aad);
  assert.equal(bytesToHex(recovered), bytesToHex(bek));
});

// ── outsider rejection: wrong device seed throws UnsealError ───────

test("unseal with wrong device seed throws UnsealError", async () => {
  const aliceSeed = new Uint8Array(32).fill(0x11);
  const bobSeed = new Uint8Array(32).fill(0x22);
  const alice = DeviceKey.fromSeed(aliceSeed);

  const bek = new Uint8Array(32).fill(0xee);
  const manifest = { kind: "kit_bundle", to_did: alice.did };
  const aad = manifestAadForWrap(manifest);
  const wrap = await sealBekForRecipient(bek, alice.did, aad);

  await assert.rejects(
    () => unsealBekFromWrap(wrap, bobSeed, aad),
    (err) => err instanceof UnsealError,
  );
});

// ── AAD-mismatch rejection: lifting a wrap into a different manifest ──

test("unseal with mismatched AAD (lift attack) throws UnsealError", async () => {
  const seed = new Uint8Array(32).fill(0x33);
  const dk = DeviceKey.fromSeed(seed);
  const bek = new Uint8Array(32).fill(0xaa);

  const m1 = { kind: "kit_bundle", to_did: dk.did, ceremony_id: "real" };
  const m2 = { kind: "kit_bundle", to_did: dk.did, ceremony_id: "spoofed" };

  const aad1 = manifestAadForWrap(m1);
  const aad2 = manifestAadForWrap(m2);

  const wrap = await sealBekForRecipient(bek, dk.did, aad1);

  // Right AAD recovers the BEK.
  const ok = await unsealBekFromWrap(wrap, seed, aad1);
  assert.equal(bytesToHex(ok), bytesToHex(bek));

  // Wrong AAD fails.
  await assert.rejects(
    () => unsealBekFromWrap(wrap, seed, aad2),
    (err) => err instanceof UnsealError,
  );
});

// ── didKeyToEd25519Pub: rejects non-Ed25519 DIDs ──────────────────

test("didKeyToEd25519Pub: rejects non-did:key inputs", () => {
  assert.throws(() => didKeyToEd25519Pub("did:vault:dev:abc"));
  assert.throws(() => didKeyToEd25519Pub(""));
});

test("didKeyToEd25519Pub: round-trips through DeviceKey.fromSeed", () => {
  const seed = new Uint8Array(32).fill(0x55);
  const dk = DeviceKey.fromSeed(seed);
  const pub = didKeyToEd25519Pub(dk.did);
  assert.equal(pub.length, 32);
  assert.equal(bytesToHex(pub), bytesToHex(dk.publicKey));
});

// ── frame check: bad frame string surfaces UnsealError ────────────

test("unseal rejects unknown frame string", async () => {
  const seed = new Uint8Array(32).fill(0x77);
  const aad = new Uint8Array(0);
  const bogus: RecipientWrap = {
    frame: "tn-sealed-box-v999",
    recipient_did: DeviceKey.fromSeed(seed).did,
    ephemeral_x25519_pub_b64: "AA",
    wrap_nonce_b64: "AA",
    wrapped_bek_b64: "AA",
  };
  await assert.rejects(
    () => unsealBekFromWrap(bogus, seed, aad),
    (err) => err instanceof UnsealError && /unsupported sealed-box frame/.test((err as Error).message),
  );
});
