// Cross-implementation sealed-object tests — the point of parity.
//
// 1. GOLDEN: consume crypto/tn-core/tests/fixtures/sealed_object_vectors.json
//    (generated by python/tools/gen_sealed_object_vectors.py, also pinned
//    by the Rust suite in crypto/tn-core/tests/sealed_object_golden.rs).
//    The TS side must verify every case's wire self-describingly, open
//    each group with the shipped recipient keys, and reproduce the
//    tamper matrix's exact failed_checks.
//
// 2. LIVE: both directions over a shared jwe ceremony using a local
//    Python with tn-proto importable (the subprocess pattern of
//    ceremony_init_row_hash_parity.test.ts). Skips cleanly when no
//    such Python exists.

import { strict as assert } from "node:assert";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { Tn, VerifyError } from "../src/tn.js";
import { unsealWithRuntime, type SealedTriple } from "../src/seal.js";
import type { Entry } from "../src/Entry.js";

const _HERE = dirname(fileURLToPath(import.meta.url));
const VECTORS_PATH = join(
  _HERE,
  "..",
  "..",
  "crypto",
  "tn-core",
  "tests",
  "fixtures",
  "sealed_object_vectors.json",
);

interface VectorCase {
  name: string;
  cipher: string;
  wire: string;
  keys: Record<string, string>;
  open_groups: Record<string, Record<string, unknown>>;
  public: Record<string, unknown>;
}

interface TamperedCase {
  name: string;
  wire: string;
  expected_failed_checks: string[];
}

interface VectorFile {
  cases: VectorCase[];
  tampered: TamperedCase[];
}

function loadVectors(): VectorFile {
  return JSON.parse(readFileSync(VECTORS_PATH, "utf8")) as VectorFile;
}

test("golden vectors: every case verifies self-describingly with no ceremony", async () => {
  const vectors = loadVectors();
  assert.ok(vectors.cases.length >= 5, "vector file must carry the full case set");
  for (const c of vectors.cases) {
    const triple = (await unsealWithRuntime(null, c.wire, { raw: true })) as SealedTriple;
    assert.equal(triple.valid.signature, true, `${c.name}: signature must verify`);
    assert.equal(triple.valid.row_hash, true, `${c.name}: row_hash must recompute`);
    // Key-less walk: nothing opens, nothing throws.
    assert.deepEqual(triple.plaintext, {}, `${c.name}: no key -> no plaintext`);
    // The public frame carries exactly the vector's public values.
    for (const [k, v] of Object.entries(c.public)) {
      assert.deepEqual(triple.envelope[k], v, `${c.name}: public field ${k}`);
    }
  }
});

test("golden vectors: shipped recipient keys open every group (btn + hibe)", async () => {
  const vectors = loadVectors();
  const base = mkdtempSync(join(tmpdir(), "tn-seal-golden-"));
  try {
    for (const c of vectors.cases) {
      const kitDir = join(base, c.name);
      mkdirSync(kitDir, { recursive: true });
      for (const [fname, b64] of Object.entries(c.keys)) {
        writeFileSync(join(kitDir, fname), Buffer.from(b64, "base64"));
      }
      for (const [group, expected] of Object.entries(c.open_groups)) {
        const triple = (await unsealWithRuntime(null, c.wire, {
          raw: true,
          asRecipient: kitDir,
          group,
        })) as SealedTriple;
        assert.deepEqual(
          triple.plaintext[group],
          expected,
          `${c.name}: group ${group} must open to the vector plaintext`,
        );
      }
    }
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("golden vectors: tamper matrix reproduces the exact failed_checks", async () => {
  const vectors = loadVectors();
  assert.ok(vectors.tampered.length >= 4, "vector file must carry the tamper matrix");
  for (const t of vectors.tampered) {
    await assert.rejects(
      unsealWithRuntime(null, t.wire),
      (e: unknown) => {
        assert.ok(e instanceof VerifyError, `${t.name}: expected VerifyError`);
        assert.deepEqual(
          e.failed_checks,
          t.expected_failed_checks,
          `${t.name}: failed_checks must match the vector exactly`,
        );
        return true;
      },
      t.name,
    );
    // verify: false still returns the triple despite the tamper.
    const triple = (await unsealWithRuntime(null, t.wire, {
      raw: true,
      verify: false,
    })) as SealedTriple;
    assert.deepEqual(triple.valid, { signature: false, row_hash: false });
  }
});

// ---------------------------------------------------------------------------
// LIVE interop — Python seals -> TS unseals, TS seals -> Python unseals.
// Same subprocess pattern as ceremony_init_row_hash_parity.test.ts.
// ---------------------------------------------------------------------------

function pickPython(): string | null {
  const candidates = [process.env["TN_PYTHON"], "python3", "python"].filter(
    (v): v is string => typeof v === "string" && v.length > 0,
  );
  for (const bin of candidates) {
    try {
      const result = spawnSync(bin, ["-c", "import tn.seal; print('ok')"], {
        encoding: "utf8",
        timeout: 10_000,
      });
      if (result.status === 0 && result.stdout.trim() === "ok") return bin;
    } catch {
      /* try next */
    }
  }
  return null;
}

// Resolve once and reuse for both the skip decision and the test body:
// each probe spawns Python with a timeout, so a second call under a
// loaded machine can flip from a binary to null and crash the body
// instead of skipping.
const PYTHON = pickPython();
const SKIP = PYTHON === null ? "Python tn-proto not available locally; runs in CI" : false;

/** Env for a Python child that keeps identity/state inside the test dir. */
function pyEnv(base: string, proj: string): NodeJS.ProcessEnv {
  return {
    ...process.env,
    TN_IDENTITY_DIR: join(base, "ident"),
    XDG_DATA_HOME: join(base, "xdg"),
    TN_PROJ: proj,
    TN_NO_STDOUT: "1",
    TN_NO_LINK: "1",
  };
}

function runPython(python: string, script: string, env: NodeJS.ProcessEnv): string {
  const r = spawnSync(python, ["-c", script], { encoding: "utf8", timeout: 60_000, env });
  if (r.status !== 0) {
    throw new Error(`python failed (${r.status}): ${r.stderr || r.stdout}`);
  }
  const lastLine = r.stdout.trim().split(/\r?\n/).filter(Boolean).pop();
  assert.ok(lastLine, `python printed no output: ${r.stdout}`);
  return lastLine;
}

// Python writer: mint a jwe ceremony, seal an object, print yaml + wire.
const PY_SEALER = `
import os, json
from pathlib import Path
proj = os.environ["TN_PROJ"]
os.chdir(proj)
import tn
tn.init(str(Path(proj) / "tn.yaml"), cipher="jwe", link=False)
sealed = tn.seal("obj.invoice.v1", receipt=False, amount=9800, customer="acme")
tn.flush_and_close()
print(json.dumps({"yaml": str(Path(proj) / "tn.yaml"), "wire": str(sealed)}))
`;

// Python reader: open a TS-minted ceremony, unseal the wire from env.
const PY_UNSEALER = `
import os, json
from pathlib import Path
proj = os.environ["TN_PROJ"]
os.chdir(proj)
import tn
tn.init(str(Path(proj) / "tn.yaml"), link=False)
wire = os.environ["TN_WIRE"]
triple = tn.unseal(wire, raw=True)
entry = tn.unseal(wire)
tn.flush_and_close()
print(json.dumps({
    "fields": entry.fields,
    "hidden_groups": entry.hidden_groups,
    "valid": triple["valid"],
}))
`;

test("live interop: Python seals, TS unseals (fields exact, checks green)", { skip: SKIP }, async () => {
  const python = PYTHON!;
  const base = mkdtempSync(join(tmpdir(), "tn-seal-py2ts-"));
  const proj = join(base, "proj");
  mkdirSync(proj, { recursive: true });
  mkdirSync(join(base, "ident"), { recursive: true });
  mkdirSync(join(base, "xdg"), { recursive: true });
  let client: Tn | null = null;
  try {
    const out = JSON.parse(runPython(python, PY_SEALER, pyEnv(base, proj))) as {
      yaml: string;
      wire: string;
    };

    // TS attaches to the SAME ceremony Python minted and opens the object.
    client = await Tn.init(out.yaml, { stdout: false });
    const triple = (await client.unseal(out.wire, { raw: true })) as SealedTriple;
    assert.equal(triple.valid.signature, true);
    assert.equal(triple.valid.row_hash, true);
    const entry = (await client.unseal(out.wire)) as Entry;
    assert.deepEqual(entry.fields, { amount: 9800, customer: "acme" });
    assert.deepEqual(entry.hidden_groups, []);

    // And ceremony-less: the wire still VERIFIES anywhere.
    const foreign = (await unsealWithRuntime(null, out.wire, { raw: true })) as SealedTriple;
    assert.equal(foreign.valid.signature, true);
    assert.equal(foreign.valid.row_hash, true);
  } finally {
    if (client) await client.close();
    rmSync(base, { recursive: true, force: true });
  }
});

test("live interop: TS seals, Python unseals (fields exact, checks green)", { skip: SKIP }, async () => {
  const python = PYTHON!;
  const base = mkdtempSync(join(tmpdir(), "tn-seal-ts2py-"));
  const proj = join(base, "proj");
  mkdirSync(proj, { recursive: true });
  mkdirSync(join(base, "ident"), { recursive: true });
  mkdirSync(join(base, "xdg"), { recursive: true });
  let client: Tn | null = null;
  try {
    client = await Tn.init(join(proj, "tn.yaml"), { cipher: "jwe", stdout: false });
    const sealed = await client.seal(
      "obj.invoice.v1",
      { amount: 9800, customer: "acme" },
      { receipt: false },
    );
    await client.close();
    client = null;

    const out = JSON.parse(
      runPython(python, PY_UNSEALER, { ...pyEnv(base, proj), TN_WIRE: String(sealed) }),
    ) as {
      fields: Record<string, unknown>;
      hidden_groups: string[];
      valid: Record<string, boolean>;
    };
    assert.deepEqual(out.fields, { amount: 9800, customer: "acme" });
    assert.deepEqual(out.hidden_groups, []);
    assert.deepEqual(out.valid, { signature: true, row_hash: true });
  } finally {
    if (client) await client.close();
    rmSync(base, { recursive: true, force: true });
  }
});

test(
  "live interop: aad-bound object crosses Python -> TS with the echo intact",
  { skip: SKIP },
  async () => {
    const python = PYTHON!;
    const base = mkdtempSync(join(tmpdir(), "tn-seal-py2ts-aad-"));
    const proj = join(base, "proj");
    mkdirSync(proj, { recursive: true });
    mkdirSync(join(base, "ident"), { recursive: true });
    mkdirSync(join(base, "xdg"), { recursive: true });
    const script = `
import os, json
from pathlib import Path
proj = os.environ["TN_PROJ"]
os.chdir(proj)
import tn
tn.init(str(Path(proj) / "tn.yaml"), cipher="jwe", link=False)
sealed = tn.seal("obj.case.v1", receipt=False, aad={"case": "A-17"}, x=1)
tn.flush_and_close()
print(json.dumps({"yaml": str(Path(proj) / "tn.yaml"), "wire": str(sealed)}))
`;
    let client: Tn | null = null;
    try {
      const out = JSON.parse(runPython(python, script, pyEnv(base, proj))) as {
        yaml: string;
        wire: string;
      };
      client = await Tn.init(out.yaml, { stdout: false });
      const entry = (await client.unseal(out.wire)) as Entry;
      assert.equal(entry.fields["x"], 1);
      // Tampering the echo flips the row hash on the TS side too.
      const tampered = JSON.parse(out.wire) as Record<string, unknown>;
      tampered["tn_aad"] = String(tampered["tn_aad"]).replace("A-17", "B-99");
      await assert.rejects(client.unseal(tampered), VerifyError);
    } finally {
      if (client) await client.close();
      rmSync(base, { recursive: true, force: true });
    }
  },
);

test(
  "live interop: public container values hash identically across impls",
  { skip: SKIP },
  async () => {
    // The row-hash preimage renders public values as Python str(value);
    // a sealed object carrying container/unicode public fields written
    // by Python must recompute byte-identically under the TS verify.
    const python = PYTHON!;
    const base = mkdtempSync(join(tmpdir(), "tn-seal-py2ts-pub-"));
    const proj = join(base, "proj");
    mkdirSync(proj, { recursive: true });
    mkdirSync(join(base, "ident"), { recursive: true });
    mkdirSync(join(base, "xdg"), { recursive: true });
    const script = `
import os, json
from pathlib import Path
proj = os.environ["TN_PROJ"]
os.chdir(proj)
import tn, yaml
yaml_path = Path(proj) / "tn.yaml"
tn.init(str(yaml_path), cipher="jwe", link=False)
tn.flush_and_close()
doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
doc["vault"]["enabled"] = False
doc["public_fields"].extend(["pv", "pv2", "pv3"])
yaml_path.write_text(yaml.safe_dump(doc, allow_unicode=True), encoding="utf-8")
tn.init(str(yaml_path))
sealed = tn.seal(
    "obj.rt.v1", receipt=False,
    pv=[1, 2, 3], pv2={"b": 2, "a": 1}, pv3="caf\\u00e9 \\u2014 na\\u00efve", x=1,
)
tn.flush_and_close()
print(json.dumps({"wire": str(sealed)}))
`;
    try {
      const out = JSON.parse(runPython(python, script, pyEnv(base, proj))) as { wire: string };
      // Ceremony-less verify is the whole point: a foreign holder with no
      // yaml recomputes the same row hash from the wire alone.
      const triple = (await unsealWithRuntime(null, out.wire, { raw: true })) as SealedTriple;
      assert.equal(triple.valid.signature, true);
      assert.equal(triple.valid.row_hash, true);
      assert.deepEqual(triple.envelope["pv"], [1, 2, 3]);
      assert.deepEqual(triple.envelope["pv2"], { b: 2, a: 1 });
      assert.equal(triple.envelope["pv3"], "café — naïve");
    } finally {
      rmSync(base, { recursive: true, force: true });
    }
  },
);
