"""Generate the shared cross-language vault-block normalization golden.

Outputs tests/fixtures/vault/normalize_cases.json (repo root), consumed by:

  * Python: python/tests/test_vault_normalize_contract.py
  * TS:     ts-sdk/test/vault_normalize_contract.test.ts

It pins the project-level `vault:` normalization (the server-independent
half of the vault.sync contract): defaults, the legacy
`ceremony.linked_vault` / `linked_project_id` bridge when no `vault:`
block is present, the `enabled: false` suppression rule, the
`sync_interval_seconds` default of 600, and the error conditions
(enabled-without-url, non-positive interval). No vault server involved.

Each consumer runs its own normalizer (`_resolve_vault_settings` /
`normalizeVaultConfig`) over (vault_block, ceremony_block) and asserts
the normalized view matches, or that an error is raised.

Expected outcomes are computed from the Python reference. Never
hand-edit; regenerate after any change to the normalizer:

    source .venv_linux/bin/activate
    python python/tools/generate_vault_normalize_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PYDIR = ROOT / "python"
sys.path.insert(0, str(PYDIR))

from tn.config import _resolve_vault_settings  # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "vault" / "normalize_cases.json"

# Each case: a `vault` block (or None) + a `ceremony` block.
CASES = [
    {"name": "no_vault_no_legacy", "vault": None, "ceremony": {}},
    {"name": "no_vault_with_legacy", "vault": None,
     "ceremony": {"linked_vault": "https://vault.tn-proto.org", "linked_project_id": "p-legacy"}},
    {"name": "enabled_default_true_with_url", "vault": {"url": "https://vault.tn-proto.org"}, "ceremony": {}},
    {"name": "enabled_false_suppresses", "vault": {"enabled": False, "url": "https://vault.tn-proto.org",
                                                   "linked_project_id": "p1"}, "ceremony": {}},
    {"name": "custom_interval", "vault": {"url": "https://vault.tn-proto.org", "sync_interval_seconds": 120},
     "ceremony": {}},
    {"name": "autosync_explicit_false", "vault": {"url": "https://vault.tn-proto.org", "autosync": False},
     "ceremony": {}},
    {"name": "full_block", "vault": {"enabled": True, "url": "https://vault.tn-proto.org",
                                     "linked_project_id": "p-remote", "autosync": True,
                                     "sync_interval_seconds": 900}, "ceremony": {}},
    {"name": "err_enabled_no_url", "vault": {"enabled": True}, "ceremony": {}},
    {"name": "err_zero_interval", "vault": {"url": "https://vault.tn-proto.org", "sync_interval_seconds": 0},
     "ceremony": {}},
    {"name": "err_negative_interval", "vault": {"url": "https://vault.tn-proto.org", "sync_interval_seconds": -5},
     "ceremony": {}},
]


def main() -> None:
    out_cases = []
    for case in CASES:
        entry: dict = {"name": case["name"], "vault": case["vault"], "ceremony": case["ceremony"]}
        try:
            s = _resolve_vault_settings(Path("tn.yaml"), case["vault"], case["ceremony"])
            entry["expected"] = {
                "error": False,
                "enabled": s.enabled,
                "url": s.url,
                "linked_project_id": s.linked_project_id,
                "autosync": s.autosync,
                "sync_interval_seconds": s.sync_interval_seconds,
            }
        except ValueError:
            entry["expected"] = {"error": True}
        out_cases.append(entry)

    fixture = {
        "_doc": (
            "Generated by python/tools/generate_vault_normalize_fixture.py. Each "
            "consumer runs its own vault normalizer over (vault, ceremony) and "
            "asserts the normalized view matches `expected`, or that it raises when "
            "expected.error is true. Never hand-edit."
        ),
        "cases": out_cases,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(out_cases)} cases)")


if __name__ == "__main__":
    main()
