"""Generate the shared cross-language recipient-wrap golden vector.

Outputs ``tests/fixtures/recipient_wraps/vector.json`` (repo root), the
single source of truth consumed identically by the Python and TS
contract tests:

  * Python: ``python/tests/test_recipient_wrap_contract.py``
  * TS:     ``ts-sdk/test/recipient_seal.test.ts``

Rust has no recipient-wrap implementation yet (the primitive lives in
the Python/TS SDKs only); see ``docs/spec-next/recipient-wraps.md``.

The vector pins a deterministic seal so the UNSEAL side is reproducible
across languages: a fixed recipient Ed25519 seed, a fixed BEK, and a
fixed representative manifest. The ephemeral X25519 key inside ``wrap``
is random per seal, but that does not matter — consumers recompute the
AAD from ``manifest`` and unseal ``wrap`` with ``ed25519_seed_hex`` to
recover ``bek_hex``. A successful unseal proves every wire-format choice
matches byte-for-byte (HKDF salt order, Ed25519->X25519 birational map,
base58btc multicodec parsing, AES-GCM tag layout, base64 padding, AAD
strip list).

Never hand-edit the output. Re-run after any change to
``tn.recipient_seal``; commit the script and the regenerated fixture
together. Run inside the codex WSL venv:

    source .venv_linux/bin/activate
    python python/tools/generate_recipient_wrap_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent  # repo root (…/protocol-core-unification)
PYDIR = ROOT / "python"
sys.path.insert(0, str(PYDIR))

from tn.recipient_seal import (  # noqa: E402
    manifest_aad_for_wrap,
    seal_bek_for_recipient,
)
from tn.signing import DeviceKey  # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "recipient_wraps" / "vector.json"

# Deterministic inputs so the fixture and every consumer agree without
# sharing live state.
_SEED = bytes(range(0x10, 0x30))  # 32 bytes: 0x10..0x2f
_BEK = bytes(range(0x40, 0x60))  # 32 bytes: 0x40..0x5f

# A representative kit_bundle manifest in the spec-next naming
# (publisher_identity / recipient_identity / head_row_hash). The seal
# path inspects only the AAD-strip keys
# (manifest_signature_b64, state.body_encryption.recipient_wrap[s]);
# everything else is bound into the AAD so a wrap minted for THIS
# manifest cannot be lifted into another. The stale wrap entries and the
# signature give the strip pass real work in every language.
_MANIFEST: dict = {
    "kind": "kit_bundle",
    "version": 1,
    "publisher_identity": "did:key:zPublisher",
    "recipient_identity": "did:key:zRecipient",
    "ceremony_id": "ceremony-fixture-1",
    "as_of": "2026-01-01T00:00:00Z",
    "scope": "kit",
    "clock": {"epoch": 7, "rotation_epoch": 1},
    "event_count": 3,
    "head_row_hash": "sha256:" + "00" * 32,
    "state": {
        "body_encryption": {
            "cipher_suite": "aes-256-gcm",
            "frame": "tn-encrypted-body-v2-zip",
            "nonce_bytes": 12,
            # Stripped by AAD computation; present so the strip pass has
            # identical work in every language.
            "recipient_wrap": {"frame": "tn-sealed-box-v1", "stale": True},
            "recipient_wraps": [{"frame": "tn-sealed-box-v1", "stale": True}],
        },
    },
    # Set AFTER the wrap in real flows; present so the strip pass must
    # find and remove it.
    "manifest_signature_b64": "STALE-SIGNATURE",
}


def main() -> None:
    recipient_identity = DeviceKey.from_private_bytes(_SEED).did
    aad = manifest_aad_for_wrap(_MANIFEST)
    wrap = seal_bek_for_recipient(_BEK, recipient_identity, aad)

    fixture = {
        "_doc": (
            "Generated by python/tools/generate_recipient_wrap_fixture.py. "
            "Consumers recompute AAD from `manifest` and unseal `wrap` with "
            "`ed25519_seed_hex` to recover `bek_hex` — proving byte-identical "
            "recipient-wrap interop. Never hand-edit; regenerate instead."
        ),
        "_aad_len": len(aad),
        "ed25519_seed_hex": _SEED.hex(),
        "recipient_identity": recipient_identity,
        "bek_hex": _BEK.hex(),
        "manifest": _MANIFEST,
        "wrap": wrap,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
