"""Build a deterministic Python-produced recipient_wrap fixture so the
TS-SDK port can prove byte-level interop.

Produces ``recipient_seal_fixture.json`` in this directory. The file
holds:

  * ``ed25519_seed_hex`` — the recipient's 32-byte Ed25519 seed.
  * ``recipient_did``   — derived ``did:key:z...`` for that seed.
  * ``bek_hex``         — the 32-byte BEK to be wrapped (deterministic
    test value).
  * ``manifest``        — a representative manifest dict with the
    fields the seal path actually inspects (plus a couple unrelated
    keys so the AAD-strip pass has work to do).
  * ``wrap``            — ``recipient_wrap`` dict produced by the
    Python ``seal_bek_for_recipient`` against the manifest's AAD.

The TS test in ``test/recipient_seal.test.ts`` loads this file,
recomputes the AAD from ``manifest``, and unseals ``wrap`` with
``ed25519_seed_hex`` — a successful unseal recovering ``bek_hex``
proves the TS port matches Python on every wire-format choice that
matters (HKDF salt order, multicodec parsing, b64 padding, AAD strip
list, AES-GCM tag layout).

Re-run after any change to recipient_seal.py:

    C:/codex/tn/.venv/Scripts/python.exe \
        tn_proto/ts-sdk/test/fixtures/build_recipient_seal_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# tn_proto/python is two levels up from ts-sdk/test/fixtures.
PYDIR = HERE.parents[2] / "python"
sys.path.insert(0, str(PYDIR))

from tn.recipient_seal import (  # noqa: E402
    manifest_aad_for_wrap,
    seal_bek_for_recipient,
)
from tn.signing import DeviceKey  # noqa: E402


# Deterministic seed and BEK so the fixture and the TS test agree on
# the inputs without sharing test fixtures live.
_SEED = bytes(range(0x10, 0x30))  # 32 bytes: 0x10..0x2f
_BEK = bytes(range(0x40, 0x60))  # 32 bytes: 0x40..0x5f

# A representative manifest. The actual seal path inspects only a few
# fields (state.body_encryption.{recipient_wrap,recipient_wraps},
# manifest_signature_b64) for the AAD strip; everything else is bound
# in the AAD so a wrap produced for THIS manifest can't be lifted into
# a different one. We include some unrelated keys to give the strip
# pass real work to do.
_MANIFEST: dict = {
    "kind": "kit_bundle",
    "ceremony_id": "ceremony-fixture-1",
    "from_did": "did:key:zPublisher",
    "to_did": "did:key:zRecipient",
    "scope": {"kit_kind": "btn"},
    "clock": {"epoch": 7, "rotation_epoch": 1},
    "event_count": 3,
    "head_row_hash_b64": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "state": {
        "body_encryption": {
            "alg": "AES-256-GCM",
            # These will be stripped by AAD computation; included so
            # the TS strip-pass has identical work.
            "recipient_wrap": {"frame": "tn-sealed-box-v1", "stale": True},
            "recipient_wraps": [
                {"frame": "tn-sealed-box-v1", "stale": True},
            ],
        },
        "extra": {"unrelated": "field"},
    },
    # signature is set AFTER the wrap; included here so the strip-pass
    # has to find and remove it.
    "manifest_signature_b64": "STALE-SIGNATURE",
}


def main() -> None:
    recipient_did = DeviceKey.from_private_bytes(_SEED).did
    aad = manifest_aad_for_wrap(_MANIFEST)
    wrap = seal_bek_for_recipient(_BEK, recipient_did, aad)

    fixture = {
        "ed25519_seed_hex": _SEED.hex(),
        "recipient_did": recipient_did,
        "bek_hex": _BEK.hex(),
        "manifest": _MANIFEST,
        "wrap": wrap,
        "_aad_len": len(aad),
        "_doc": (
            "Generated by build_recipient_seal_fixture.py. The TS test "
            "recomputes AAD from `manifest` and unseals `wrap` with "
            "`ed25519_seed_hex` to confirm byte-identical interop."
        ),
    }

    out = HERE / "recipient_seal_fixture.json"
    out.write_text(json.dumps(fixture, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
