"""Cross-language recipient-wrap contract (Python side).

Consumes the shared golden vector at
``tests/fixtures/recipient_wraps/vector.json`` (generated by
``python/tools/generate_recipient_wrap_fixture.py``) and proves the
Python ``tn.recipient_seal`` implementation unseals it to the expected
BEK. The TS side asserts the same vector in
``ts-sdk/test/recipient_seal.test.ts``; a wrap that unseals identically
under both proves byte-level interop on every wire-format choice (HKDF
salt order, Ed25519->X25519 birational map, base58btc multicodec
parsing, AES-GCM tag layout, base64 padding, AAD strip list).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tn.recipient_seal import (
    UnsealError,
    WRAP_FRAME,
    manifest_aad_for_wrap,
    seal_bek_for_recipient,
    unseal_bek_from_wrap,
)
from tn.signing import DeviceKey

REPO = Path(__file__).resolve().parents[2]
FIXTURE = REPO / "tests" / "fixtures" / "recipient_wraps" / "vector.json"


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_unseal_shared_golden_recovers_bek() -> None:
    """Headline cross-language assertion: unseal the shared wrap and
    recover the exact BEK the producer wrapped."""
    f = _fixture()
    seed = bytes.fromhex(f["ed25519_seed_hex"])
    expected_bek = bytes.fromhex(f["bek_hex"])

    # The recipient identity derived locally must match the fixture, or a
    # base58btc / multicodec drift would silently pick a different key.
    assert DeviceKey.from_private_bytes(seed).did == f["recipient_identity"]
    assert f["wrap"]["frame"] == WRAP_FRAME
    assert f["wrap"]["recipient_identity"] == f["recipient_identity"]

    aad = manifest_aad_for_wrap(f["manifest"])
    assert len(aad) == f["_aad_len"]

    bek = unseal_bek_from_wrap(f["wrap"], seed, aad)
    assert bek == expected_bek


def test_aad_strips_signature_and_wraps() -> None:
    """AAD binds everything except the signature and the wrap block(s)."""
    f = _fixture()
    aad = manifest_aad_for_wrap(f["manifest"]).decode("utf-8")
    assert "manifest_signature_b64" not in aad
    assert "recipient_wrap" not in aad  # covers recipient_wrap + recipient_wraps
    assert "STALE-SIGNATURE" not in aad
    # A bound field survives.
    assert "ceremony-fixture-1" in aad


def test_aad_does_not_mutate_caller_manifest() -> None:
    f = _fixture()
    before = json.dumps(f["manifest"], sort_keys=True)
    manifest_aad_for_wrap(f["manifest"])
    after = json.dumps(f["manifest"], sort_keys=True)
    assert before == after


def test_seal_unseal_round_trip() -> None:
    seed = bytes([i + 1 for i in range(32)])
    did = DeviceKey.from_private_bytes(seed).did
    bek = bytes(range(0x80, 0xA0))
    manifest = {"kind": "kit_bundle", "recipient_identity": did,
                "state": {"body_encryption": {"cipher_suite": "aes-256-gcm"}}}
    aad = manifest_aad_for_wrap(manifest)

    wrap = seal_bek_for_recipient(bek, did, aad)
    assert wrap["frame"] == WRAP_FRAME
    assert wrap["recipient_identity"] == did

    assert unseal_bek_from_wrap(wrap, seed, aad) == bek


def test_outsider_seed_is_rejected() -> None:
    alice = bytes([0x11] * 32)
    bob = bytes([0x22] * 32)
    alice_did = DeviceKey.from_private_bytes(alice).did
    bek = bytes([0xEE] * 32)
    aad = manifest_aad_for_wrap({"kind": "kit_bundle", "recipient_identity": alice_did})
    wrap = seal_bek_for_recipient(bek, alice_did, aad)

    with pytest.raises(UnsealError):
        unseal_bek_from_wrap(wrap, bob, aad)


def test_lifted_wrap_fails_on_mismatched_aad() -> None:
    seed = bytes([0x33] * 32)
    did = DeviceKey.from_private_bytes(seed).did
    bek = bytes([0xAA] * 32)
    aad1 = manifest_aad_for_wrap({"kind": "kit_bundle", "ceremony_id": "real"})
    aad2 = manifest_aad_for_wrap({"kind": "kit_bundle", "ceremony_id": "spoofed"})
    wrap = seal_bek_for_recipient(bek, did, aad1)

    assert unseal_bek_from_wrap(wrap, seed, aad1) == bek
    with pytest.raises(UnsealError):
        unseal_bek_from_wrap(wrap, seed, aad2)


def test_unknown_frame_is_rejected() -> None:
    seed = bytes([0x77] * 32)
    bogus = {
        "frame": "tn-sealed-box-v999",
        "recipient_identity": DeviceKey.from_private_bytes(seed).did,
        "ephemeral_x25519_pub_b64": "AA",
        "wrap_nonce_b64": "AA",
        "wrapped_bek_b64": "AA",
    }
    with pytest.raises(UnsealError):
        unseal_bek_from_wrap(bogus, seed, b"")
