"""Cross-language BTN wire contract (Python side).

The BTN binary wire format (ciphertext + reader-kit + publisher-state
layouts) is owned by Rust (`crypto/tn-btn`). This test proves the
Python binding decodes the SAME shared golden ciphertext that the Rust
test (`crypto/tn-core/tests/cipher_btn.rs`) and the TS/WASM test
(`ts-sdk/test/btn_wire_contract.test.ts`) decode — i.e. no SDK
reinterprets the wire independently.

Shared golden: `crypto/tn-core/tests/fixtures/btn_vectors.json`
(generated by `python/tools/generate_rust_fixtures.py::gen_btn`).

See `docs/spec-next/btn-wire.md`.
"""

from __future__ import annotations

import json
from pathlib import Path

from tn._native import btn as tn_btn

REPO = Path(__file__).resolve().parents[2]
FIXTURE = REPO / "crypto" / "tn-core" / "tests" / "fixtures" / "btn_vectors.json"

# BTN wire header: magic 0xB7, version 0x01, then a kind byte.
BTN_MAGIC = 0xB7
BTN_VERSION = 0x01
KIND_CIPHERTEXT = 0x01
KIND_READER_KIT = 0x02
KIND_PUBLISHER_STATE = 0x03


def _vec() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_btn_decrypts_shared_golden() -> None:
    v = _vec()
    kit = bytes.fromhex(v["reader_kit_bytes_hex"])
    ct = bytes.fromhex(v["ciphertext_hex"])
    expected = bytes.fromhex(v["plaintext_hex"])

    assert tn_btn.decrypt(kit, ct) == expected


def test_btn_wire_headers_match_layout() -> None:
    """Pin the binary header (magic/version/kind) of each wire record so a
    layout drift is caught even before decrypt."""
    v = _vec()
    ct = bytes.fromhex(v["ciphertext_hex"])
    kit = bytes.fromhex(v["reader_kit_bytes_hex"])
    state = bytes.fromhex(v["publisher_state_bytes_hex"])

    for blob, kind in (
        (ct, KIND_CIPHERTEXT),
        (kit, KIND_READER_KIT),
        (state, KIND_PUBLISHER_STATE),
    ):
        assert blob[0] == BTN_MAGIC
        assert blob[1] == BTN_VERSION
        assert blob[2] == kind


def test_btn_publisher_state_roundtrips() -> None:
    """The publisher-state wire blob parses back into a PublisherState
    (wire deserialize/serialize parity within the Python binding)."""
    v = _vec()
    state = bytes.fromhex(v["publisher_state_bytes_hex"])
    pub = tn_btn.PublisherState.from_bytes(state)
    assert pub.to_bytes() == state
