"""Cross-language vault-block normalization contract (Python side).

The server-independent half of the vault.sync contract: how the
project-level ``vault:`` block (and the legacy ``ceremony.linked_*``
fallback) normalizes into the runtime's vault view. Consumes the shared
golden tests/fixtures/vault/normalize_cases.json (generated by
python/tools/generate_vault_normalize_fixture.py); the TS side asserts
the same cases in ts-sdk/test/vault_normalize_contract.test.ts.

See docs/spec-next/vault-sync.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tn.config import _resolve_vault_settings

REPO = Path(__file__).resolve().parents[2]
FIXTURE = REPO / "tests" / "fixtures" / "vault" / "normalize_cases.json"


def _cases() -> list[dict]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"]


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_vault_normalize_matches_shared_golden(case: dict) -> None:
    expected = case["expected"]
    if expected.get("error"):
        with pytest.raises(ValueError):
            _resolve_vault_settings(Path("tn.yaml"), case["vault"], case["ceremony"])
        return

    s = _resolve_vault_settings(Path("tn.yaml"), case["vault"], case["ceremony"])
    assert s.enabled == expected["enabled"]
    assert s.url == expected["url"]
    assert s.linked_project_id == expected["linked_project_id"]
    assert s.autosync == expected["autosync"]
    assert s.sync_interval_seconds == expected["sync_interval_seconds"]
