"""Cross-language absorb vault-metadata-adoption contract (Python side).

Consumes tests/fixtures/absorb/vault_adoption_cases.json (generated by
python/tools/generate_absorb_vault_adoption_fixture.py) and proves the
Python project-seed vault-adoption rule matches the shared golden. The
TS side asserts the same cases in
ts-sdk/test/absorb_vault_adoption_contract.test.ts.

Rule: absorbing a root-authoritative
project_seed over an existing project fills empty vault url /
linked_project_id, never overwrites non-empty local values, and treats
`vault.enabled: false` as adoption-blocking.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml as _yaml

from tn.absorb import _project_seed_vault_yaml_patch

REPO = Path(__file__).resolve().parents[2]
FIXTURE = REPO / "tests" / "fixtures" / "absorb" / "vault_adoption_cases.json"


def _cases() -> list[dict]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"]


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_vault_adoption_matches_shared_golden(case: dict) -> None:
    patched, vault_only = _project_seed_vault_yaml_patch(
        case["existing_yaml"].encode("utf-8"),
        case["incoming_yaml"].encode("utf-8"),
    )
    expected = case["expected"]
    assert (patched is not None) == expected["changed"]
    assert vault_only == expected["vault_only"]

    effective = patched.decode("utf-8") if patched is not None else case["existing_yaml"]
    doc = _yaml.safe_load(effective) or {}
    vault = doc.get("vault") if isinstance(doc, dict) else None

    if expected["result"] is None:
        assert not isinstance(vault, dict)
        return

    assert isinstance(vault, dict)
    exp = expected["result"]
    assert vault.get("url", "") == exp["url"]
    assert vault.get("linked_project_id", "") == exp["linked_project_id"]
    assert vault.get("enabled") == exp["enabled"]
