"""Python re-verifies + re-opens the committed sealed-object vectors.

``crypto/tn-core/tests/fixtures/sealed_object_vectors.json`` is
generated by ``python/tools/gen_sealed_object_vectors.py`` and consumed
by the Rust runner (``crypto/tn-core/tests/sealed_object_golden.rs``).
This guard proves the committed vectors stay openable by the Python
reference itself: if either implementation drifts, its run of the
shared vectors goes red.

Every open here goes through the ``as_recipient`` path, which needs no
active ceremony — exactly how a foreign holder of the kit material
would open the object.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

import tn
from tn import VerifyError

FIXTURES = (
    Path(__file__).resolve().parents[2] / "crypto" / "tn-core" / "tests" / "fixtures"
)
DATA = json.loads(
    (FIXTURES / "sealed_object_vectors.json").read_text(encoding="utf-8")
)


@pytest.fixture(autouse=True)
def _no_active_ceremony():
    # The as_recipient path must work standalone; make sure no prior
    # test left a runtime open, and leave none behind.
    try:
        tn.flush_and_close()
    except Exception:  # noqa: BLE001 — nothing to close is fine
        pass
    yield
    try:
        tn.flush_and_close()
    except Exception:  # noqa: BLE001
        pass


@pytest.mark.parametrize("case", DATA["cases"], ids=lambda c: c["name"])
def test_sealed_object_verifies_and_opens(case, tmp_path):
    # Expected public fields surface verbatim on the parsed envelope.
    env = json.loads(case["wire"])
    for k, v in case["public"].items():
        assert env[k] == v, f"public key {k!r} must surface verbatim"

    # Key material lands in a bare directory, as an absorbed kit would.
    for fname, b64 in case["keys"].items():
        (tmp_path / fname).write_bytes(base64.b64decode(b64))

    for group, expected in case["open_groups"].items():
        triple = tn.unseal(case["wire"], raw=True, as_recipient=tmp_path, group=group)
        assert triple["valid"] == {"signature": True, "row_hash": True}
        assert triple["plaintext"][group] == expected


@pytest.mark.parametrize("case", DATA["tampered"], ids=lambda c: c["name"])
def test_tampered_object_fails_expected_checks(case, tmp_path):
    # Verification runs before any key loading, so an empty keystore
    # directory suffices.
    with pytest.raises(VerifyError) as exc:
        tn.unseal(case["wire"], as_recipient=tmp_path, group="default")
    assert exc.value.failed_checks == case["expected_failed_checks"]
