"""Top-level summary written as `summary.md` — the human entry point."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


def _load_json(p: Path) -> dict:
    if not p.exists():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def _package_summary(symbols: list[dict]) -> list[tuple[str, int]]:
    counts: Counter[str] = Counter()
    for s in symbols:
        parts = s["qualname"].split(".")
        if len(parts) < 2:
            continue
        pkg = ".".join(parts[:2])
        counts[pkg] += 1
    return sorted(counts.items(), key=lambda kv: kv[0])


def write_summary(artifacts_dir: Path) -> Path:
    symbols = _load_json(artifacts_dir / "surface_inventory.json").get("symbols", [])
    deps = _load_json(artifacts_dir / "deps.json")
    extensions = _load_json(artifacts_dir / "extension_points.json")
    env_vars = _load_json(artifacts_dir / "env_vars.json").get("env_vars", [])
    flags = _load_json(artifacts_dir / "flag_inventory.json").get("flags", [])
    rust = _load_json(artifacts_dir / "rust_surface.json").get("items", [])
    coverage = _load_json(artifacts_dir / "coverage_manifest.json")

    public = [s for s in symbols if s.get("is_public")]
    in_all_count = sum(1 for s in symbols if s.get("in_all") is True)

    lines: list[str] = [
        "# tn-protocol audit baseline — Phase 0 summary",
        "",
        f"_Generated by `python -m tools.introspect run-all`._",
        "",
        "## Coverage proof",
        "",
    ]
    if coverage:
        lines.append(f"- Files visited: **{coverage.get('files_visited', 0)}** Python, **{coverage.get('rust_files_visited', 0)}** Rust")
        lines.append(f"- Total Python LOC: **{coverage.get('python_loc', 0)}**")
        lines.append(f"- Total Python AST nodes: **{coverage.get('python_ast_nodes', 0)}**")
        lines.append(f"- Total Rust LOC: **{coverage.get('rust_loc', 0)}**")
    else:
        lines.append("_No coverage_manifest.json found._")
    lines.append("")

    lines.append("## Python surface")
    lines.append("")
    lines.append(f"- Symbols total: **{len(symbols)}** ({len(public)} public, {len(symbols) - len(public)} private)")
    lines.append(f"- Symbols declared in `__all__`: **{in_all_count}**")
    lines.append("- By top-level package:")
    for pkg, count in _package_summary(symbols):
        lines.append(f"  - `{pkg}` — {count} symbols")
    lines.append("")

    reverse = deps.get("reverse_edges", {})
    importer_counts = sorted(
        ((mod, len(imps)) for mod, imps in reverse.items() if imps),
        key=lambda kv: (-kv[1], kv[0]),
    )[:15]
    if importer_counts:
        lines.append("### Top 15 most-imported modules")
        for mod, count in importer_counts:
            lines.append(f"- `{mod}` ({count} importers)")
        lines.append("")

    lines.append("## Environment variables")
    lines.append("")
    lines.append(f"Discovered: **{len(env_vars)}** distinct names.")
    if env_vars:
        for ev in sorted(env_vars, key=lambda e: e["name"])[:30]:
            lines.append(f"- `{ev['name']}` — {len(ev['call_sites'])} site(s)")
    lines.append("")

    lines.append("## Flag inventory")
    lines.append("")
    lines.append(f"Bool / Optional[bool] kwargs: **{len(flags)}**.")
    if flags:
        # Show the top 20 most-used flags by call-site count
        ranked = sorted(flags, key=lambda f: (-f.get("call_site_count", 0), f["function_qualname"]))[:20]
        lines.append("Top 20 by call-site count (where call sites = locations passing this kwarg by name):")
        lines.append("")
        for f in ranked:
            lines.append(
                f"- `{f['function_qualname']}({f['kwarg_name']}={f.get('default')})` "
                f"at `{f['file']}:{f['lineno']}` — {f.get('call_site_count', 0)} call sites"
            )
    lines.append("")

    emit_hooks = extensions.get("emit_hooks", [])
    log_events = extensions.get("tn_log_event_types", [])
    lines.append("## Extension points")
    lines.append("")
    lines.append(f"- `emit()` hooks: **{len(emit_hooks)}**")
    lines.append(f"- `tn.log()` event types (string-literal first arg): **{len(log_events)}**")
    if log_events:
        lines.append("")
        lines.append("First 30 event types:")
        for h in sorted(log_events, key=lambda x: x["name"])[:30]:
            lines.append(f"- `{h['name']}` ({len(h['call_sites'])} sites)")
    lines.append("")

    lines.append("## Rust surface")
    lines.append("")
    lines.append(f"Public Rust items found: **{len(rust)}**")
    by_kind: Counter[str] = Counter(item["kind"] for item in rust)
    for kind, count in sorted(by_kind.items()):
        lines.append(f"- `{kind}`: {count}")
    lines.append("")

    lines.append("## Files")
    lines.append("")
    lines.append("| Artifact | Purpose |")
    lines.append("|---|---|")
    for name, purpose in [
        ("surface_inventory.json / .html", "every Python function/class with signature, decorators, public/private, in-`__all__` flag"),
        ("deps.json / .mmd / .dot", "module-level import graph"),
        ("extension_points.json / .html", "emit() hooks + tn.log() event types with call sites"),
        ("env_vars.json / .html", "every env var the code reads (TN_*, CP_TN_*, etc.)"),
        ("flag_inventory.json / .html", "bool / Optional[bool] kwargs across the SDK"),
        ("phantom_regrounding.md", "the 19 phantom-features-audit items, re-grounded against current AST"),
        ("rust_surface.json", "public Rust items in tn-core / tn-btn / tn-proto-py"),
        ("admin_coupling.dot / .svg", "import graph zoomed to admin*.py modules"),
        ("classes.mmd / packages.mmd", "pyreverse class + package diagrams"),
        ("coverage_manifest.json", "proof: every file visited, LOC and AST node counts"),
        ("MANIFEST.json", "source-hash manifest for staleness detection"),
    ]:
        lines.append(f"| `{name}` | {purpose} |")
    lines.append("")

    lines.append("## Re-running")
    lines.append("")
    lines.append("```bash")
    lines.append("cd tn-protocol/python")
    lines.append("../../.venv/Scripts/python.exe -m tools.introspect run-all")
    lines.append("```")
    lines.append("")

    out = artifacts_dir / "summary.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
