// Generate ts-sdk/src/version.ts from package.json's "version".
//
// Wired into the `prebuild` / `pretest` / `prepack` lifecycle so SDK_VERSION
// can never lag package.json — the drift that produced 0.6.1-vs-0.6.2 is now
// structurally impossible. tools/bump.py also writes version.ts directly for
// immediate consistency after a bump; this is the build-time safety net.
//
// Idempotent: writes only when the content changes, so it won't dirty the
// working tree on a no-op build.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

const out = `// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.
// Run \`npm run gen:version\` (or any build/test) to regenerate.

export const SDK_VERSION = ${JSON.stringify(version)};

/** User-Agent for every outbound HTTP call the SDK makes (vault, account,
 * wallet, bootstrap). Mirrors Python's dynamic \`tn-proto/<version>\`. */
export const USER_AGENT = \`tn-proto-ts/\${SDK_VERSION}\`;
`;

const target = join(root, "src", "version.ts");
const existing = (() => {
  try {
    return readFileSync(target, "utf8");
  } catch {
    return null;
  }
})();

if (existing !== out) {
  writeFileSync(target, out);
  console.log(`gen-version: wrote src/version.ts (${version})`);
} else {
  console.log(`gen-version: src/version.ts already current (${version})`);
}
